import React, { useState } from 'react';
import { X, Printer, Copy, Check, ShieldCheck, FileText, Download } from 'lucide-react';

export default function PolicyReportModal({ isOpen, onClose, simulationData, city, selectedZoneId }) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !simulationData) return null;

  const {
    baseline_lst,
    simulated_lst,
    temp_reduction_degC,
    cost_breakdown,
    roi_efficiency,
    shap_attribution
  } = simulationData;

  const topDriver = shap_attribution?.[0]?.feature_name || 'Built-up Index';

  const reportText = `
================================================================================
URBAN HEAT MITIGATION EXECUTABLE POLICY STRATEGY REPORT
City Target: ${city} | Target Zone: ${selectedZoneId}
================================================================================

1. EXECUTIVE SUMMARY & TARGET ASSESSMENT
--------------------------------------------------------------------------------
- Baseline Surface Temperature (LST): ${baseline_lst.toFixed(2)} °C
- Simulated Surface Temperature (LST): ${simulated_lst.toFixed(2)} °C
- Net Projected Thermal Cooling: ${temp_reduction_degC.toFixed(2)} °C Drop
- Primary Heat Driver Identified (XAI SHAP): ${topDriver}

2. CAPITAL EXPENDITURE & MITIGATION FINANCIAL ALLOCATION
--------------------------------------------------------------------------------
- Urban Greening & Tree Canopy: ₹${(cost_breakdown?.urban_greening || 0).toLocaleString('en-IN')}
- Reflective / Cool Roof Coating: ₹${(cost_breakdown?.cool_roofs || 0).toLocaleString('en-IN')}
- Permeable Surface De-paving: ₹${(cost_breakdown?.depaving || 0).toLocaleString('en-IN')}
- TOTAL CAPITAL BUDGET: ₹${(cost_breakdown?.total_inr || cost_breakdown?.total_usd || 0).toLocaleString('en-IN')}
- Efficiency Metric: ${roi_efficiency.toFixed(2)} °C Cooling per ₹1 Lakh invested

3. STAKEHOLDER ACTION RECOMMENDATIONS
--------------------------------------------------------------------------------
1. Mandate high-albedo solar-reflective rooftop coatings for all concrete structures in ${selectedZoneId}.
2. Expand high-density tree canopy along major transit corridors to offset vegetative loss (NDVI).
3. Introduce municipal tax incentives for commercial de-paving initiatives.

Generated by ThermaGrid — AI Urban Heat Island Mitigation System.
`.trim();

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md">
      <div className="glass-panel w-full max-w-2xl bg-slate-900 border border-slate-700 rounded-xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
        {/* Modal Header */}
        <div className="p-4 bg-slate-950 border-b border-slate-800 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-emerald-400" />
            <h3 className="text-base font-bold text-white">Executive Policy Strategy Brief</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded text-slate-400 hover:text-white hover:bg-slate-800 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-5 text-xs text-slate-300">
          <div className="flex items-center justify-between p-3 bg-slate-800/60 rounded-lg border border-slate-700">
            <div>
              <span className="text-slate-400 block text-[11px]">Jurisdiction Target:</span>
              <span className="font-bold text-white text-sm">{city} — {selectedZoneId}</span>
            </div>
            <div className="text-right">
              <span className="text-slate-400 block text-[11px]">Simulated Heat Drop:</span>
              <span className="font-extrabold text-emerald-400 text-sm">↓ {temp_reduction_degC.toFixed(2)} °C</span>
            </div>
          </div>

          <div>
            <h4 className="font-bold text-slate-100 text-xs uppercase tracking-wider mb-2 text-emerald-400">
              1. Key Interventions & Investment Summary
            </h4>
            <div className="grid grid-cols-2 gap-3">
              <div className="p-3 bg-slate-950 rounded border border-slate-800">
                <span className="text-slate-400 block text-[10px]">Baseline LST</span>
                <span className="text-base font-bold text-rose-400">{baseline_lst.toFixed(2)} °C</span>
              </div>
              <div className="p-3 bg-slate-950 rounded border border-slate-800">
                <span className="text-slate-400 block text-[10px]">Target Post-Mitigation LST</span>
                <span className="text-base font-bold text-emerald-400">{simulated_lst.toFixed(2)} °C</span>
              </div>
              <div className="p-3 bg-slate-950 rounded border border-slate-800">
                <span className="text-slate-400 block text-[10px]">Total Investment</span>
                <span className="text-base font-bold text-white">₹{(cost_breakdown?.total_inr || cost_breakdown?.total_usd || 0).toLocaleString('en-IN')}</span>
              </div>
              <div className="p-3 bg-slate-950 rounded border border-slate-800">
                <span className="text-slate-400 block text-[10px]">Efficiency Index</span>
                <span className="text-base font-bold text-amber-400">{roi_efficiency.toFixed(2)} °C / ₹1L</span>
              </div>
            </div>
          </div>

          <div>
            <h4 className="font-bold text-slate-100 text-xs uppercase tracking-wider mb-2 text-sky-400">
              2. SHAP Explainability Breakdown
            </h4>
            <div className="space-y-1 bg-slate-950 p-3 rounded border border-slate-800">
              {shap_attribution?.map((item) => (
                <div key={item.feature_key} className="flex justify-between py-1 border-b border-slate-900 last:border-0">
                  <span className="text-slate-300">{item.feature_name}:</span>
                  <span className={`font-semibold ${item.impact_degC > 0 ? 'text-rose-400' : 'text-sky-400'}`}>
                    {item.impact_degC > 0 ? `+${item.impact_degC}` : item.impact_degC} °C
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Raw Markdown Output Box */}
          <div>
            <h4 className="font-bold text-slate-100 text-xs uppercase tracking-wider mb-2 text-slate-300">
              3. Raw Markdown Document
            </h4>
            <pre className="bg-slate-950 p-3 rounded border border-slate-800 text-[11px] font-mono text-emerald-300 whitespace-pre-wrap">
              {reportText}
            </pre>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex justify-between items-center">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold rounded text-xs transition cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied!' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-4 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded text-xs transition cursor-pointer"
          >
            <Printer className="w-4 h-4" />
            <span>Print Strategy Brief</span>
          </button>
        </div>
      </div>
    </div>
  );
}
